In [1]:
#NumPy Sorting Arrays
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [2]:
#You can also sort arrays of strings, or any other data type:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [3]:
#Sort a boolean array:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [4]:
#Sorting a 2-D Array
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
