In [1]:
#Random Numbers in NumPy
#Generate Random Number
from numpy import random

x = random.randint(100)

print(x)


36


In [2]:
#Generate Random Float
from numpy import random

x = random.rand()

print(x)

0.32689559416499714


In [3]:
#Generate Random Array
from numpy import random

x=random.randint(100, size=(5))

print(x)

[50 78 28 34 63]


In [4]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[20 88 42 22 80]
 [57 73 53 97 90]
 [77 58 78 86 13]]


In [5]:
#The rand() method also allows you to specify the shape of the array.
from numpy import random

x = random.rand(5)

print(x)

[0.12984193 0.32735255 0.23823082 0.92258905 0.07423508]


In [6]:
#Generate a 2-D array with 3 rows, each row containing 5 random numbers:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.68508846 0.06042404 0.75542776 0.02763421 0.16462505]
 [0.43390138 0.31875877 0.39118287 0.29885277 0.8990476 ]
 [0.65205354 0.68511309 0.95048939 0.90071093 0.57906691]]


In [7]:
#Generate Random Number From Array
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

5


In [8]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 9 7 7 3]
 [5 5 9 9 3]
 [9 9 9 7 7]]
